config/urls.py
from django.contrib import admin
from django.urls import path, include
# from pybo.views import base_views
from kenchi import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('kenchi/', include('kenchi.urls')),
    path('', views.index, name='index')  # '/'에 해당되는 path

]

handler404 = 'common.views.page_not_found'

pybo/urls.py
from django.urls import path
from . import views
from .views import base_views, question_views, answer_views

app_name = 'pybo'

urlpatterns = [
    # base_views.py
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),

    # question_views.py
    path('question/create/',
         question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/',
         question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/',
         question_views.question_delete, name='question_delete'),
    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),

    # answer_views.py
    path('answer/create/<int:question_id>/',
         answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/',
         answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/',
         answer_views.answer_delete, name='answer_delete'),
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name='answer_vote'),
]

pybo/models.py
from django.db import models
from django.contrib.auth.models import User


class Question(models.Model):
    # User 모델은 django.contrib.auth 앱이 제공하는 사용자 모델로 회원 가입시 데이터 저장에 사용했던 모델이다.
    # 계정이 삭제되면 이 계정이 작성한 질문을 모두 삭제하라는 의미.
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_question')  # 추천인 추가


    def __str__(self):
        return self.subject

class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_answer')

pybo/forms.py
from django import forms
from pybo.models import Question, Answer

# 장고의 폼은 일반 폼(forms.Form)과 모델 폼(forms.ModelForm)이 있는데 모델 폼은 모델(Model)과
# 연결된 폼으로 폼을 저장하면 연결된 모델의 데이터를 저장할 수 있는 폼이다.
# 모델폼은 이너 클래스인 Meta 클래스가 반드시 필요하다.
# Meta 클래스에는 사용할 모델과 모델의 속성을 적어야 한다.

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question  # 사용할 모델
        fields = ['subject', 'content']  # QuestionForm에서 사용할 Question 모델의 속성
        # widgets = {
        #     'subject': forms.TextInput(attrs={'class': 'form-control'}),
        #     'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
        # }
        labels = {
            'subject': '제목',
            'content': '내용',
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

pybo/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..forms import AnswerForm
from ..models import Question, Answer


@login_required(login_url='common:login')
def answer_create(request, question_id):
        """
        pybo 답변등록
        """
        print("답변등록")
        question = get_object_or_404(Question, pk=question_id)
        if request.method == "POST":
                print("post요청이다")
                form = AnswerForm(request.POST)
                if form.is_valid():
                        print("is_valid")
                        answer = form.save(commit=False)
                        answer.author = request.user  # author 속성에 로그인 계정 저장
                        answer.create_date = timezone.now()
                        answer.question = question
                        answer.save()
                        # resolve_url은 실제 호출되는 URL 문자열을 리턴하는 장고의 함수이다.
                        return redirect('{}#answer_{}'.format(resolve_url('pybo:detail', question_id=question.id), answer.id))
        else:
                form = AnswerForm()

                # return HttpResponseNotAllowed('Only POST is possible.')
        context = {'question': question, 'form': form}
        return render(request, 'pybo/question_detail.html', context)

        # 1 ForeignKey로 연결되어있을때 사용할 수 있는 방법
        ##question.answer_set.create(content=request.POST.get('content'), create_date=timezone.now())
        # 2 Answer 모델을 직접 사용하는 방법
        ##answer = Answer(question=question, content=request.POST.get('content'), create_date=timezone.now())
        ##answer.save()
        ##return redirect('pybo:detail', question_id=question.id)


@login_required(login_url='common:login')
def answer_modify(request, answer_id):
        answer = get_object_or_404(Answer, pk=answer_id)
        if request.user != answer.author:
                messages.error(request, '수정권한이 없습니다.')
                return redirect('pybo:detail', question_id=answer.question.id)
        if request.method == "POST":
                form = AnswerForm(request.POST, instance=answer)
                if form.is_valid():
                        answer = form.save(commit=False)
                        answer.modify_date = timezone.now()
                        answer.save()
                        return redirect('{}#answer_{}'.format(resolve_url('pybo:detail', question_id=answer.question.id), answer.id))
        else:
                form = AnswerForm(instance=answer)
        context = {'answer': answer, 'form': form}
        return render(request, 'pybo/answer_form.html', context)



@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다')
    else:
        answer.delete()
    return redirect('pybo:detail', question_id=answer.question.id)


@login_required(login_url='common:login')
def answer_vote(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user == answer.author:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        answer.voter.add(request.user)
    return redirect('{}#answer_{}'.format(resolve_url('pybo:detail', question_id=answer.question.id), answer.id))

pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from ..models import Question
import logging
logger = logging.getLogger('pybo')


# def index(request):
#     logger.info("INFO 레벨로 출력")
#     return render(request, 'kenchi/index.html', {})


def index(request):
    logger.info("INFO 레벨로 출력")
    page = request.GET.get('page', '1')  # 페이지  default
    kw = request.GET.get('kw', '')  # 검색어
    question_list = Question.objects.order_by('-create_date')
    if kw:
        question_list = question_list.filter(
            # filter 함수에서 모델 속성에 접근하기 위해서는 이처럼 __(언더바 2개) 를 이용하여 하위 속성에 접근할 수 있다.
            # subject__contains=kw 대신 subject__icontains=kw 을 사용하면 대소문자를 가리지 않고 찾아 준다.
            Q(subject__icontains=kw) |  # 제목 검색 제목에 kw 문자열이 포함되었는지를 의미.
            Q(content__icontains=kw) |  # 내용 검색
            Q(answer__content__icontains=kw) |  # 답변 내용 검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
        ).distinct()
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    logger.info(paginator)
    page_obj = paginator.get_page(page)  # 해당 페이지의 데이터만 조회하도록 쿼리가 변경된다.
    logger.info(page_obj)
    context = {'question_list': page_obj, 'page': page, 'kw': kw}
    return render(request, 'pybo/question_list.html', context)


def detail(request, question_id):
    # question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)

pybo/views/question_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..forms import QuestionForm
from ..models import Question


@login_required(login_url='common:login')
def question_create(request):
        # POST 요청
        if request.method == 'POST':
                print("question_create POST 요청으로 들어왔다.")
                form = QuestionForm(request.POST)  # request.POST에 담긴 subject, content 값이 QuestionForm의 subject, content 속성에 자동으로 저장되어 객체가 생성
                # 폼이 유효하다면: form에 저장된 subject, content의 값이 올바르지 않다면 form에는 오류 메시지가 저장
                if form.is_valid():
                        question = form.save(commit=False)  # 임시 저장하여 question 객체를 리턴
                        question.author = request.user  # author 속성에 로그인 계정 저장
                        question.create_date = timezone.now()  # 실제 저장을 위해 작성일시를 설정
                        question.save()  # 데이터를 실제로 저장
                        return redirect('pybo:index')
        # GET 요청
        else:
                form = QuestionForm()
        context = {'form': form}
        # return render(request, 'pybo/question_form1.html', context)
        return render(request, 'pybo/question_form.html', context)


@login_required(login_url='common:login')
def question_modify(request, question_id):
        question = get_object_or_404(Question, pk=question_id)
        if request.user != question.author:
                messages.error(request, '수정권한이 없습니다.')  # messages는 장고가 제공하는 모듈로 넌필드 오류(non-field error)를 발생시킬 경우에 사용.
                return redirect('pybo:detail', question_id=question_id)
        if request.method == "POST":
                form = QuestionForm(request.POST, instance=question)  # request.POST의 값으로 덮어쓴다.
                if form.is_valid():
                        question = form.save(commit=False)
                        question.modify_date = timezone.now()  # 수정일시 저장
                        question.save()
                        return redirect('pybo:detail', question_id=question.id)
        else:
                form = QuestionForm(instance=question)  # GET요청인 경우 질문수정 화면에 조회된 질문의 제목과 내용이 반영될 수 있도록.
                                                        # 폼 생성시 이처럼 instance 값을 지정하면 폼의 속성 값이 instance의 값으로 채워진다.
        context = {'form': form}
        return render(request, 'pybo/question_form.html', context)


@login_required(login_url='common:login')
def question_delete(request, question_id):
        question = get_object_or_404(Question, pk=question_id)
        if request.user != question.author:
                messages.error(request, '삭제권한이 없습니다.')
                return redirect('pybo:detail', question_id=question_id)
        question.delete()
        return redirect('pybo:index')


@login_required(login_url='common:login')
def question_vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user == question.author:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다')
    else:
        question.voter.add(request.user)
    return redirect('pybo:detail', question_id=question.id)

templates/pybo/answer_form.html
{% extends 'base.html' %}
{% block content %}
<!-- 답변 수정-->
<div class="container my-3">
    <form method="post">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea class="form-control" name="content" id="content"
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/pybo/question_detail.html
{% extends 'kenchi/base.html' %}

{% load pybo_filter %}

{% block content %}

    <div class="detail-wrap">
        <div class="inner">
            {% if messages %}
        <div class="alert alert-danger my-3" role="alert">
            {% for message in messages %}
            <strong>{{ message.tags }}</strong>
            <ul><li>{{ message.message }}</li></ul>
            {% endfor %}
        </div>
        {% endif %}
            <div class="title-area">
                <h1 class="detail-title">{{ question.subject }}</h1>
            </div>
            <div class="area-wrap">
                <div class="detail-title-area">{{ question.content|mark }}</div>
                {% if question.modify_date %}
                <div class="created">
                    <div class="writer">modified at</div>
                    <div class="created-at">{{ question.modify_date }}</div>
                </div>
                {% endif %}
                <div class="modified">
                    <div class="writer">{{ question.author.username }}</div>
                    <div class="created-at">{{ question.create_date }}</div>
                </div>
                <div class="recommend">
                    <a href="javascript:void(0)" data-uri="{% url 'pybo:question_vote' question.id  %}" class="question-recommend"> 추천
                        <span class="badge">{{question.voter.count}}</span>
                    </a>
                </div>
                {% if request.user == question.author %}
                <div class="modify">
                    <a href="{% url 'pybo:question_modify' question.id %}" class="question-modify">수정</a>
                </div>
                <div class="delete">
                    <a href="javascript:void(0)" class="question-delete" data-uri="{% url 'pybo:question_delete' question.id  %}">삭제</a>
                </div>
                {% endif %}
            </div>


            <div class="title-area">
                <h1 class="detail-title2">{{question.answer_set.count}}개의 답변이 있습니다.</h1>
            </div>

            {% for answer in question.answer_set.all %}
            <div class="area-wrap">
                <div class="detail-title-area">{{ answer.content }}</div>
                {% if question.modify_date %}
                <div class="created">
                    <div class="writer">modified at</div>
                    <div class="created-at">{{ question.modify_date }}</div>
                </div>
                {% endif %}
                <div class="modified">
                    <div class="writer">{{ answer.author.username }}</div>
                    <div class="created-at">{{ answer.create_date }}</div>
                </div>
                <div class="recommend">
                    <a href="javascript:void(0)" data-uri="{% url 'pybo:question_vote' answer.id  %}" class="question-recommend"> 추천
                        <span class="badge">{{answer.voter.count}}</span>
                    </a>
                </div>
                {% if request.user == answer.author %}
                <div class="modify">
                    <a href="{% url 'pybo:question_modify' question.id %}" class="question-modify">수정</a>
                </div>
                <div class="delete">
                    <a href="javascript:void(0)" class="question-delete" data-uri="{% url 'pybo:question_delete' question.id  %}">삭제</a>
                </div>
                {% endif %}
            </div>
            {% endfor %}

            <div class="title-area">
                <h1 class="detail-title2">답변내용</h1>
            </div>
            <form action="{% url 'pybo:answer_create' question.id %}" method="post">
                {% csrf_token %}
                 <!-- 오류표시 Start -->
            {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                {% for field in form %}
                {% if field.errors %}
                <div>
                    <strong>{{ field.label }}</strong>
                    {{ field.errors }}
                </div>
                {% endif %}
                {% endfor %}
            </div>
            {% endif %}
            <!-- 오류표시 End -->
                <textarea {% if not user.is_authenticated %}disabled{% endif %} name="" id="" cols="30" rows="10" class="area-wrap2"></textarea>
            </form>


            <input class="answer-submit" type="submit" value="답변등록">


        </div>
    </div>
    {% endblock %}
    {% block script %}
    <script type='text/javascript'>
    const delete_elements = document.getElementsByClassName("delete");
    Array.from(delete_elements).forEach(function(element) {
        element.addEventListener('click', function() {
            if(confirm("정말로 삭제하시겠습니까?")) {
                location.href = this.dataset.uri;
            };
        });
    });
    const recommend_elements = document.getElementsByClassName("recommend");
    Array.from(recommend_elements).forEach(function(element) {
        element.addEventListener('click', function() {
            if(confirm("정말로 추천하시겠습니까?")) {
                location.href = this.dataset.uri;
            };
        });
    });
    </script>


{% endblock %}

templates/pybo/question_form.html
{% extends 'kenchi/base.html' %}
{% block content %}

<div class="register-wrap">

    <div class="inner-register">
        <!-- 오류표시 Start -->
          {% if form.errors %}
          <div class="alert alert-danger" role="alert">
              {% for field in form %}
              {% if field.errors %}
              <div>
                  <strong>{{ field.label }}</strong>
                  {{ field.errors }}
              </div>
              {% endif %}
              {% endfor %}
          </div>
          {% endif %}
          <!-- 오류표시 End -->
        <h2 class="label">질문등록</h2>
        <form method="post">
            {% csrf_token %}
        <div class="r-title">제목</div>
        <input class="r-title-input"  name="subject" id="subject" type="text" value="{{ form.subject.value|default_if_none:'' }}" placeholder="제목을 입력하세요.">
        <div class="r-title2" >내용</div>
        <textarea class="r-content-input" name="content" id="content" cols="30" rows="10" placeholder="내용을 입력하세요.">{{ form.content.value|default_if_none:'' }}</textarea>
        <input class="r-save" type="submit" value="저장하기">
        </form>
    </div>

</div>














<!--<div class="container">-->
<!--  <h5 class="my-3 border-bottom pb-2">질문등록</h5>-->
<!--&lt;!&ndash; action 속성을 지정하지 않았다. form 태그에 action 속성을 지정하지 않으면 현재 페이지의 URL 이 디폴드 action으로 설정된다. &ndash;&gt;-->

<!--  <form method="post">-->
<!--    {% csrf_token %}-->
<!--    &lt;!&ndash; 오류표시 Start &ndash;&gt;-->
<!--        {% if form.errors %}-->
<!--        <div class="alert alert-danger" role="alert">-->
<!--            {% for field in form %}-->
<!--            {% if field.errors %}-->
<!--            <div>-->
<!--                <strong>{{ field.label }}</strong>-->
<!--                {{ field.errors }}-->
<!--            </div>-->
<!--            {% endif %}-->
<!--            {% endfor %}-->
<!--        </div>-->
<!--        {% endif %}-->
<!--        &lt;!&ndash; 오류표시 End &ndash;&gt;-->
<!--        <div class="mb-3">-->
<!--            <label for="subject" class="form-label">제목</label>-->
<!--            <input type="text" class="form-control" name="subject" id="subject"-->
<!--                   value="{{ form.subject.value|default_if_none:'' }}">-->
<!--        </div>-->
<!--        <div class="mb-3">-->
<!--            <label for="content" class="form-label">내용</label>-->
<!--            <textarea class="form-control" name="content"-->
<!--                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>-->
<!--        </div>-->

<!--    <button type="submit" class="btn btn-primary">저장하기</button>-->
<!--  </form>-->
<!--</div>-->
{% endblock %}

templates/pybo/question_form_auto.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <h5 class="my-3 border-bottom pb-2">질문등록</h5>
<!-- action 속성을 지정하지 않았다. form 태그에 action 속성을 지정하지 않으면 현재 페이지의 URL 이 디폴드 action으로 설정된다. -->

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">저장하기</button>
  </form>
</div>
{% endblock %}

templates/pybo/question_list.html
{% extends 'kenchi/base.html' %}

{% load pybo_filter %}

{% block content %}


<!-- Question -->
<section class="questions">

    <div class="inner">
        <div class="top-item">
            <a href="{% url 'pybo:question_create' %}" class="question-regist">Question Registration</a>
            <input type="text" id="search_kw" class="search-question" placeholder="통합검색">
            <button type="button" id="search-question-btn" class="search-question-btn">Search</button>
        </div>
        <div class="board-wrap">
            <div class="board-list">
                <div class="top">
                    <div class="num">번호</div>
                    <div class="title">제목</div>
                    <div class="writer">글쓴이</div>
                    <div class="date">작성일시</div>
                </div>
                {% if question_list %}
                {% for question in question_list %}
                <div>
                    <div class="num">{{question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}
                    </div>
                    <div class="title">
                        <a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a>
                        {% if question.answer_set.count > 0 %}
                        <div class="title-answer-count">({{ question.answer_set.count }})</div>
                        {% endif %}
                    </div>
                    <div class="writer">{{ question.author.username }}</div>
                    <div class="date">{{ question.create_date }}</div>
                </div>
                {% endfor %}
                {% else %}
                <tr>
                    <td colspan="4">질문이 없습니다.</td>
                </tr>
                {% endif %}
            </div>
        </div>

        <!--==========================-->

        <!-- 페이징처리 시작 -->
        <div class="inner-page">
            <ul class="pagination">
                <!-- 이전페이지 -->
                <div>
                    <!-- 이전 페이지가 있는 경우에는 "이전" 링크가 활성화되게-->
                    {% if question_list.has_previous %}
                    <li class="page-item-left">
                        <a class="page-link" data-page="{{ question_list.previous_page_number }}"
                           href="javascript:void(0)">이전</a>
                    </li>
                    {% else %}
                    <li class="page-item-left disabled">
                        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전2</a>
                    </li>
                    {% endif %}
                    <!-- 페이지리스트 -->
                    <!--        페이지 리스트를 루프 돌면서 해당 페이지로 이동할 수 있는 링크를 랭성-->
                    {% for page_number in question_list.paginator.page_range %}
                    <!--        현재 페이지를 의미하는 question_list.number 보다 5만큼 크거나 작은 값만 표시되도록-->
                    {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
                    {% if page_number == question_list.number %}
                    <!--        현재 페이지와 같을 경우에는 active클래스를 적용하여 강조-->
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" data-page="{{ page_number }}" href="javascript:void(0)">{{ page_number }}</a>
                    </li>
                    {% else %}
                    <li class="page-item">
                        <a class="page-link" data-page="{{ page_number }}" href="javascript:void(0)">{{ page_number }}</a>
                    </li>
                    {% endif %}
                    {% endif %}
                    {% endfor %}
                    <!-- 다음페이지 -->
                    <!--        다음 페이지가 있는 경우에는 "다음" 링크가 활성화되게-->
                    {% if question_list.has_next %}
                    <li class="page-item-right">
                        <a class="page-link" data-page="{{ question_list.next_page_number }}" href="javascript:void(0)">다음</a>
                    </li>
                    {% else %}
                    <li class="page-item-right disabled">
                        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음3</a>
                    </li>
                    {% endif %}
                </div>
            </ul>
            <!-- 페이징처리 끝 -->

            <!--            ===========================-->


            <!--                    &lt;!&ndash; 페이징처리 시작 &ndash;&gt;-->
            <!--    <ul class="pagination justify-content-center">-->
            <!--        &lt;!&ndash; 이전페이지 &ndash;&gt;-->
            <!--        &lt;!&ndash; 이전 페이지가 있는 경우에는 "이전" 링크가 활성화되게&ndash;&gt;-->
            <!--        {% if question_list.has_previous %}-->
            <!--        <li class="page-item">-->
            <!--            <a class="page-link" data-page="{{ question_list.previous_page_number }}" href="javascript:void(0)">이전</a>-->
            <!--        </li>-->
            <!--        {% else %}-->
            <!--        <li class="page-item disabled">-->
            <!--            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>-->
            <!--        </li>-->
            <!--        {% endif %}-->
            <!--        &lt;!&ndash; 페이지리스트 &ndash;&gt;-->
            <!--&lt;!&ndash;        페이지 리스트를 루프 돌면서 해당 페이지로 이동할 수 있는 링크를 랭성&ndash;&gt;-->
            <!--        {% for page_number in question_list.paginator.page_range %}-->
            <!--&lt;!&ndash;        현재 페이지를 의미하는 question_list.number 보다 5만큼 크거나 작은 값만 표시되도록&ndash;&gt;-->
            <!--        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}-->
            <!--        {% if page_number == question_list.number %}-->
            <!--&lt;!&ndash;        현재 페이지와 같을 경우에는 active클래스를 적용하여 강조&ndash;&gt;-->
            <!--        <li class="page-item active" aria-current="page">-->
            <!--            <a class="page-link" data-page="{{ page_number }}" href="javascript:void(0)">{{ page_number }}</a>-->
            <!--        </li>-->
            <!--        {% else %}-->
            <!--        <li class="page-item">-->
            <!--            <a class="page-link" data-page="{{ page_number }}" href="javascript:void(0)">{{ page_number }}</a>-->
            <!--        </li>-->
            <!--        {% endif %}-->
            <!--        {% endif %}-->
            <!--        {% endfor %}-->
            <!--        &lt;!&ndash; 다음페이지 &ndash;&gt;-->
            <!--&lt;!&ndash;        다음 페이지가 있는 경우에는 "다음" 링크가 활성화되게&ndash;&gt;-->
            <!--        {% if question_list.has_next %}-->
            <!--        <li class="page-item">-->
            <!--            <a class="page-link" data-page="{{ question_list.next_page_number }}" href="javascript:void(0)">다음</a>-->
            <!--        </li>-->
            <!--        {% else %}-->
            <!--        <li class="page-item disabled">-->
            <!--            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>-->
            <!--        </li>-->
            <!--        {% endif %}-->
            <!--    </ul>-->
            <!--    &lt;!&ndash; 페이징처리 끝 &ndash;&gt;-->

        </div>
    </div>
</section>
<form id="searchForm" method="get" action="{% url 'pybo:index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock %}

{% block script %}
<script type='text/javascript'>
console.log("question_list.html 직접 작성한 스크립트 연동 성공")

const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
    });
});
const btn_search = document.getElementById("search-question-btn");
btn_search.addEventListener('click', function() {
    document.getElementById('kw').value = document.getElementById('search_kw').value;
    document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
    document.getElementById('searchForm').submit();
});


</script>
{% endblock %}