config/urls.py
from django.contrib import admin
from django.urls import path, include
# from pybo.views import base_views
from kenchi import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('kenchi/', include('kenchi.urls')),
    path('', views.index, name='index')  # '/'에 해당되는 path

]

handler404 = 'common.views.page_not_found'

kenchi/urls.py
from django.urls import path
from . import views


app_name = 'kenchi'


urlpatterns = [
    path('', views.index, name='index'),
]

pybo/urls.py
from django.urls import path
from . import views
from .views import base_views, question_views, answer_views

app_name = 'pybo'

urlpatterns = [
    # base_views.py
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),

    # question_views.py
    path('question/create/',
         question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/',
         question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/',
         question_views.question_delete, name='question_delete'),
    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),

    # answer_views.py
    path('answer/create/<int:question_id>/',
         answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/',
         answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/',
         answer_views.answer_delete, name='answer_delete'),
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name='answer_vote'),
]

kenchi/models.py
from django.db import models

# Create your models here.

pybo/models.py
from django.db import models
from django.contrib.auth.models import User


class Question(models.Model):
    # User 모델은 django.contrib.auth 앱이 제공하는 사용자 모델로 회원 가입시 데이터 저장에 사용했던 모델이다.
    # 계정이 삭제되면 이 계정이 작성한 질문을 모두 삭제하라는 의미.
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_question')  # 추천인 추가


    def __str__(self):
        return self.subject

class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_answer')

kenchi/views.py
from django.shortcuts import render

import logging
logger = logging.getLogger('kenchi')

# Create your views here.


def index(request):
    logger.info("INFO 레벨로 출력")
    return render(request, 'kenchi/index.html', {})

pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from ..models import Question
import logging
logger = logging.getLogger('pybo')


# def index(request):
#     logger.info("INFO 레벨로 출력")
#     return render(request, 'kenchi/index.html', {})


def index(request):
    logger.info("INFO 레벨로 출력")
    page = request.GET.get('page', '1')  # 페이지  default
    kw = request.GET.get('kw', '')  # 검색어
    question_list = Question.objects.order_by('-create_date')
    if kw:
        question_list = question_list.filter(
            # filter 함수에서 모델 속성에 접근하기 위해서는 이처럼 __(언더바 2개) 를 이용하여 하위 속성에 접근할 수 있다.
            # subject__contains=kw 대신 subject__icontains=kw 을 사용하면 대소문자를 가리지 않고 찾아 준다.
            Q(subject__icontains=kw) |  # 제목 검색 제목에 kw 문자열이 포함되었는지를 의미.
            Q(content__icontains=kw) |  # 내용 검색
            Q(answer__content__icontains=kw) |  # 답변 내용 검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
        ).distinct()
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    logger.info(paginator)
    page_obj = paginator.get_page(page)  # 해당 페이지의 데이터만 조회하도록 쿼리가 변경된다.
    logger.info(page_obj)
    context = {'question_list': page_obj, 'page': page, 'kw': kw}
    return render(request, 'pybo/question_list.html', context)


def detail(request, question_id):
    # question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)

templates/kenchi/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>kenchi.co.kr</title>

    <link rel="icon" href="{% static 'images/circle_mirror_me.jpg' %}">

    <!-- 오픈 그래프 -->
    <meta property="og:type" content="website" />
    <meta property="og:site_name" content="Kenchi" />
    <meta property="og:title" content="kenchi.co.kr" />
    <meta property="og:description" content="켄치파파의 연습용 사이트" />
    <meta property="og:image" content="{% static 'images/circle_mirror_me.jpg' %}" />
    <meta property="og:url" content="http://kenchi.co.kr" />

    <!-- 트위터 카드 -->
    <meta property="twitter:card" content="summary" />
    <meta property="twitter:site" content="Kenchi" />
    <meta property="twitter:title" content="kenchi.co.kr" />
    <meta property="twitter:description" content="켄치파파의 연습용 사이트" />
    <meta property="twitter:image" content="{% static 'images/circle_mirror_me.jpg' %}" />
    <meta property="twitter:url" content="http://kenchi.co.kr" />

    <!-- css 초기화 -->
    <link href="https://cdn.jsdelivr.net/npm/reset-css@5.0.1/reset.min.css" rel="stylesheet" />

    <!-- Google Fonts(Nanum Gothic Regular 400 bold 700) -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nanum+Gothic:wght@400;700&display=swap" rel="stylesheet">

    <!-- Google material icons -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />

    <!-- gsap & ScrollToPlugin cdn -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.11.4/gsap.min.js" integrity="sha512-f8mwTB+Bs8a5c46DEm7HQLcJuHMBaH/UFlcgyetMqqkvTcYg4g5VXsYR71b3qC82lZytjNYvBj2pf0VekA9/FQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.11.4/ScrollToPlugin.min.js" integrity="sha512-tQFq+nb/TSS648SDzWbSj0A67t4I1PFzR0U6Oi/yEYFyUbAIwg74SOCbr7t2X1Rn+iln7sYwfh8y+z7p0gddOw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<!--    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">-->

    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    <!-- YOUTUBE -->
    <script defer src="{% static 'js/youtube.js' %}"></script>

<!--    <script defer src="{% static 'bootstrap.min.js' %}"></script>-->

    <script defer src="{% static 'js/main.js' %}"></script>


</head>
<body>

<!-- header -->
{% include "kenchi/header.html" %}

<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->

<!-- footer -->
{% include "kenchi/footer.html" %}

<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->

</body>
</html>

templates/kenchi/footer.html
{% load static %}

<!-- FOOTER -->
     <footer>
        <div class="inner">
            <ul class="menu">
                <li><a href="javascript:void(0)" class="green">개인정보처리방침</a></li>
                <li><a href="javascript:void(0)">영상정보처리기기 운영관리 방침</a></li>
                <li><a href="javascript:void(0)">홈페이지 이용약관</a></li>
                <li><a href="javascript:void(0)">위치정보 이용약관</a></li>
                <li><a href="javascript:void(0)">윤리경영 핫라인</a></li>
            </ul>
            <div class="btn-group">
                <a href="javascript:void(0)" class="btn">찾아오시는 길</a>
                <a href="javascript:void(0)" class="btn">사이트 맵</a>
                <a href="javascript:void(0)" class="btn">도움말</a>
            </div>
            <div class="info">
                <span>사업자등록번호 000-000000</span>
                <span>(주)켄치 코리아 대표이사 Kenchi Papa</span>
                <span>TEL : 00) 0000-0000 / FAX : 00) 0000-0000</span>
                <span>개인정보 책임자 : Kenchi Papa</span>
            </div>
            <p class="copyright">
                &copy; <span class="this-year"></span> Kenchi Company. All Rights Reserved.
            </p>
            <img src="{% static 'images/kenchi_text_logo.png' %}" alt="" class="logo" />
        </div>
    </footer>

templates/kenchi/header.html
{% load static %}

<header>
        <div class="inner">

            <a href="/" class="logo">
                <img src="{% static 'images/kenchi_text_logo.png' %}" alt="kenchi_logo">
            </a>

            <!-- SUB-MENU -->
            <div class="sub-menu">
                <ul class="menu">
                    {% if user.is_authenticated %}
                    <li>
                        <a href="javascript:void(0)">USER : {{ user.username }} </a>
                    </li>
                    <li>
                        <a href="/common/logout">LOG OUT</a>
                    </li>
                    {% else %}
                    <li>
                        <a href="/common/login">SIGN IN</a>
                    </li>
                    {% endif %}
                    {% if not user.is_authenticated %}
                    <li>
                        <a href="/common/signup">SIGN UP</a>
                    </li>
                    {% endif %}
                    <li>
                        <a href="javascript:void(0)">ABOUT</a>
                    </li>
                    <li>
                        <a href="javascript:void(0)">CONTACT</a>
                    </li>
                </ul>
                <div class="search">
                    <input type="text" />
                    <div class="material-icons">search</div>
                </div>
            </div>

            <!-- MAIN-MENU -->
            <ul class="main-menu">
                <li class="item">
                    <div class="item__name">ETC</div>
                    <div class="item__contents">
                        <div class="contents__menu">
                        <ul class="inner">
                            <li>
                            <h4>가나</h4>
                            <ul>
                                <li>다라마바 사아</li>
                                <li>자차카타 파하</li>
                                <li>가나다라 마바사아</li>
                            </ul>
                            </li>
                            <li>
                            <h4>자차카타 파하</h4>
                            <ul>
                                <li>도레미</li>
                                <li>파솔라시도 레미파솔</li>
                                <li>라시도레미</li>
                                <li>파솔라시</li>
                                <li>도레미파</li>
                                <li>솔라</li>
                                <li>시도</li>
                                <li>도레미파솔 라시도</li>
                            </ul>
                            </li>
                            <li>
                            <h4>도레 미파솔</h4>
                            <ul>
                                <li>라시도레 미파솔 라시도레</li>
                                <li>미파솔 라시도레 미파</li>
                                <li>솔 라시 도레미 파솔라시도레</li>
                                <li>미파솔® 라시 도레 미파솔</li>
                            </ul>
                            </li>
                            <li>
                            <h4>도레미 파솔라 시도레 미</h4>
                            <ul>
                                <li>파솔 라시도</li>
                                <li>레미 파솔</li>
                                <li>라시도 레미 파솔</li>
                                <li>라시 도레미</li>
                                <li>파솔라시 도레미파 솔라시도 레미파 솔</li>
                            </ul>
                            </li>
                        </ul>
                        </div>
                        <div class="contents__texture">
                        <div class="inner">
                            <h4>라시 도레미파 솔라 시도</h4>
                            <p>도레미파 솔라시도레 미파솔라 시도레 미파솔라시도.</p>
                            <h4>레미파 솔라시 도레미 파</h4>
                            <p>솔라시도 레미파 솔라 시도레 미파솔 라시도 레미파솔라.</p>
                        </div>
                        </div>
                    </div>
                </li>
                <li class="item">
                    <a href="/pybo" class="item__name__underline">Question</a>
                </li>
            </ul>
        </div>
    </header>

templates/kenchi/index.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>kenchi.co.kr</title>

    <link rel="icon" href="{% static 'images/circle_mirror_me.jpg' %}">

    <!-- 오픈 그래프 -->
    <meta property="og:type" content="website" />
    <meta property="og:site_name" content="Kenchi" />
    <meta property="og:title" content="kenchi.co.kr" />
    <meta property="og:description" content="켄치파파의 연습용 사이트" />
    <meta property="og:image" content="{% static 'images/circle_mirror_me.jpg' %}" />
    <meta property="og:url" content="http://kenchi.co.kr" />

    <!-- 트위터 카드 -->
    <meta property="twitter:card" content="summary" />
    <meta property="twitter:site" content="Kenchi" />
    <meta property="twitter:title" content="kenchi.co.kr" />
    <meta property="twitter:description" content="켄치파파의 연습용 사이트" />
    <meta property="twitter:image" content="{% static 'images/circle_mirror_me.jpg' %}" />
    <meta property="twitter:url" content="http://kenchi.co.kr" />

    <!-- css 초기화 -->
    <link href="https://cdn.jsdelivr.net/npm/reset-css@5.0.1/reset.min.css" rel="stylesheet" />

    <!-- Google Fonts(Nanum Gothic Regular 400 bold 700) -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nanum+Gothic:wght@400;700&display=swap" rel="stylesheet">

    <!-- Google material icons -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />

    <!-- gsap & ScrollToPlugin cdn -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.11.4/gsap.min.js" integrity="sha512-f8mwTB+Bs8a5c46DEm7HQLcJuHMBaH/UFlcgyetMqqkvTcYg4g5VXsYR71b3qC82lZytjNYvBj2pf0VekA9/FQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.11.4/ScrollToPlugin.min.js" integrity="sha512-tQFq+nb/TSS648SDzWbSj0A67t4I1PFzR0U6Oi/yEYFyUbAIwg74SOCbr7t2X1Rn+iln7sYwfh8y+z7p0gddOw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<!--    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">-->

    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    <!-- YOUTUBE -->
    <script defer src="{% static 'js/youtube.js' %}"></script>

<!--    <script defer src="{% static 'bootstrap.min.js' %}"></script>-->

    <script defer src="{% static 'js/main.js' %}"></script>


</head>
<body>

<!-- header -->
{% include "kenchi/header.html" %}

    <!-- VISUAL -->
    <section class="visual">
        <div class="inner">
            <div class="title fade-in">
                <img src="{% static 'images/K.png' %}" alt="K" class="k" />
            </div>
            <div class="fade-in">
                <img src="{% static 'images/E.png' %}" alt="E" class="e" />
            </div>
            <div class="fade-in">
                <img src="{% static 'images/N.png' %}" alt="N" class="n" />
            </div>
            <div class="fade-in">
                <img src="{% static 'images/C.png' %}" alt="C" class="c" />
            </div>
            <div class="fade-in">
                <img src="{% static 'images/H.png' %}" alt="H" class="h" />
            </div>
            <div class="fade-in">
                <img src="{% static 'images/I.png' %}" alt="I" class="i">
            </div>
            <div class="fade-in">
                <img src="{% static 'images/cat_foot.png' %}" alt="cat foot" class="cat-foot floating ">
            </div>
            <div class="fade-in">
                <img src="{% static 'images/cat_foot2.png' %}" alt="cat foot2" class="cat-foot2 floating2">
            </div>
        </div>
    </section>


    <!-- YOUTUBE VIDEO -->
    <section class="youtube">
        <div class="youtube__area">
            <div id="player"></div>
        </div>
        <div class="youtube__cover"></div>
    </section>

<!-- footer -->
{% include "kenchi/footer.html" %}

</body>
</html>

templates/kenchi/test.html
 질문 목록
<div class="container my-3">
    <div class="row my-3">
        <div class="col-6">
            <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">질문 등록하기</a>
        </div>
        <div class="col-6">
            <div class="input-group">
                <input type="text" id="search_kw" class="form-control" value="{{ kw|default_if_none:'' }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                </div>
            </div>
        </div>
    </div>
    <table class="table">
        <thead>
        <tr class="text-center table-dark">
            <th>번호</th>
            <th style="width:50%">제목</th>
            <th>글쓴이</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr class="text-center">
            <td>
                <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}

            </td>
            <td class="text-center">
                <a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a>
            {% if question.answer_set.count > 0 %}
                <span class="text-danger small mx-2">{{ question.answer_set.count }}</span>
            {% endif %}
            </td>
<!-- 글쓴이 추가-->
            <td>{{ question.author.username }}</td>
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="4">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        <!-- 이전 페이지가 있는 경우에는 "이전" 링크가 활성화되게-->
        {% if question_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.previous_page_number }}" href="javascript:void(0)">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
<!--        페이지 리스트를 루프 돌면서 해당 페이지로 이동할 수 있는 링크를 랭성-->
        {% for page_number in question_list.paginator.page_range %}
<!--        현재 페이지를 의미하는 question_list.number 보다 5만큼 크거나 작은 값만 표시되도록-->
        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
        {% if page_number == question_list.number %}
<!--        현재 페이지와 같을 경우에는 active클래스를 적용하여 강조-->
        <li class="page-item active" aria-current="page">
            <a class="page-link" data-page="{{ page_number }}" href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" data-page="{{ page_number }}" href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
<!--        다음 페이지가 있는 경우에는 "다음" 링크가 활성화되게-->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.next_page_number }}" href="javascript:void(0)">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->


    </div>
    <form id="searchForm" method="get" action="{% url 'index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
    </form>